<?php
$current_category_id = $block->getCurrentCategoryId();
$categoryObj = $this->categoryRepository->get($current_category_id);
$subcategories = $categoryObj->getChildrenCategories();
?>
<ul class="catalog-grid" id="categories-list">
    <?php foreach ($subcategories as $subcat) { ?>
        <li class="categorie-grid-item
            categorie-item
            categorie-item-info
            categorie-item-details
            ">
            <a href="<?= $subcat->getUrl(); ?>"
               class="categorie-grid-tem__link banner"
               aria-label="<?= $subcat->getName(); ?>">
                <?php $title = $this->getCategoryData($subcat->getId())->getData('additional_headline') ?>
                <?php $title = isset($title) ? $title : $subcat->getName(); ?>
                <img title="<?= $title ?>" src="<?= $this->getImageUrl($subcat->getId()); ?>" alt="<?= $subcat->getName(); ?>"/>
                <div class="banner__content">
                    <p class="banner__text"><?= $subcat->getName(); ?></p>
                    <span class="banner__icon">
                        <svg class="icon arrow-right__icon" role="presentation" focusable="false">
                            <title>Arrow right icon</title>
                            <use href="<?= $block->escapeUrl($block->getViewFileUrl("images/icons-sprite.svg#arrow-right")) ?>"></use>
                        </svg>
                    </span>
                </div>
            </a>
        </li>
    <?php } ?>
</ul>
